server:
  port: 8083
spring:
  application:
    name: 'transportador'
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka