spring:
  application:
    name: 'fornecedor'
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8082
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
